### PR TITLE
Added a note about AutoPro and Turnstiles on Axon

### PR DESCRIPTION
**Pull request by xdlivecat**
This is a common question so i thought it would be good to add it here.

### CODE REVIEW

**Comment by xdlivecat** [comment]
did i do this correctly i have no idea lol

**Review by prpldev — CHANGES_REQUESTED** [review]
e-portal reference is above, maybe add as a note to that instead of adding a whole new section

**Comment by xdlivecat** [comment]
i changed it i think idk brain not working

**Review by prpldev — CHANGES_REQUESTED** [review]
close pr as this problem is fixed in #17.

**Pull request closed without merging**
